num1= input('Digite o primeiro numero')
num2= input('Digite o segundo numero')
s = int(num1) + int(num2)
#print('A soma entre',num1,'+',num2,'Igual a',s)
print('A soma entre {} e {} vale {}'.format(num1,num2,s))
